# Site settings
title: Your Internet Friend, Jimmy Marks
email: jimmy@jimmymarks.com
description: > # this means to ignore newlines until "baseurl:"
  Jimmy Marks is a UX Designer/Researcher/Writer and a Front-End Developer. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jimmymarks.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

navigation:

  - title: Case Studies
    url: /case-studies/
  - title: Resume
    url: /resume/
  - title: Contact
    url: /contact/
